### ISSUE TITLE
"Volxbibel" verlangsamt dein iPhone möglicherweise

### ISSUE THREAD

**Issue by webernetz** [volxbibel/ios-2010#3]
Diese Meldung kommt aktuell beim Starten der App. zusätzlich noch mit der Unterzeile:
"Der Entwickler muss diese App aktualisieren, um dessen Kompatibilität zu verbessern."

**Comment by powtac** [comment]
Wird mit dem nächsten "iOS 11 Kompatibilitätsupdate" gefixt.

**Comment by powtac** [comment]
... Die App ist in Review...
